### ISSUE TITLE
support for multiple categories

### ISSUE THREAD

**Issue by SriSatyaLokesh** [thiagorossener/jekflix-template#102]
For now we are asking user to pick only single category.
how to make it multiple?

**Comment by algorithmor** [comment]
A post will always belong to only one category. There are tags to indicate sub-topics in that category that the post is related to, which is pretty much a standard these days. Can you share more details on the goal here.

**Comment by SriSatyaLokesh** [comment]
Usually one post can relate to more than one category.
I made that change to this template.
Support for multiple categories. Will raise a PR and screenshots of results.

**Comment by algorithmor** [comment]
Great @SriSatyaLokesh . My thought is that a post should always be under one main category. Tags are available to indicate other areas that the post also relates to. e.g. **Database** can be a category and then if we talking about specific aspects of a database, e.g. _#mongodb_ _#performancetuning_ those can be tags. Categories should be less in number and tags have no limit. I think @thiagorossener can decide better on this one.

**Comment by SriSatyaLokesh** [comment]
I agree, Thanks for that @algorithmor

**Comment by thiagorossener** [comment]
Thank you @SriSatyaLokesh and @algorithmor for your thoughts on this.

The way I see it, you should make the categories the more generic as possible and use tags to complement it.

Notice that even if we had multiple categories, that could potentially break the home page layout or create an unpleasant appearance.

If the intent with multiple categories is to have a nice page for those posts, maybe a better solution is to create a tag page that works like the category page.

To make it clearer, the template could have a page like:
https://jekflix.rossener.com/category/life/

But with an URL like:
https://jekflix.rossener.com/tag/travel

Anyway, it's just an idea. Feel free to submit a PR with your solution and I promise I will analyze.
