### ISSUE TITLE
How to change the Link image whose default image is "JEKFLIX"

### ISSUE THREAD

**Issue by YeonghyeonKO** [thiagorossener/jekflix-template#103]
I've changed many defaults you'd set, but when I copy and paste my url, then the representative image of my github.io is still "JEKFLIX" image. How can I change it with my own image?

[
![제목 없음](https://user-images.githubusercontent.com/46114393/85587083-6d0d2780-b67c-11ea-8da5-330d32e46f24.jpg)
](url)

Also, when I've exchanged default images into new images designed and entered through my cell phone (Android), I could see link image has been changed but it isn't same in the desktop version as well as url image I wrote above.

![image](https://user-images.githubusercontent.com/46114393/85588850-0852cc80-b67e-11ea-9595-44275358da90.png)

**Comment by thiagorossener** [comment]
Hey @YeonghyeonKO, you need to replace the images in `/src/img/icons`. You can see all those images in [here](https://github.com/thiagorossener/jekflix-template/tree/master/src/img/icons).

**Comment by YeonghyeonKO** [comment]
![image](https://user-images.githubusercontent.com/46114393/85665271-2f4ce500-b6f6-11ea-9650-7543fdbb03f3.png)
I've already changed images. New images and icons are well applied in Mobile, but not in Desktop environment.

**Comment by thiagorossener** [comment]
Hmmm this is strange. Maybe it's a cache issue, did you try hard refresh the page?

**Comment by YeonghyeonKO** [comment]
You're right. I refreshed cache and it has changed to the image I had designed. Thanks for your answer!

**Comment by thiagorossener** [comment]
Glad you got it!
