### ISSUE TITLE
paginate: -1 broke main page

### ISSUE THREAD

**Issue by Party4Bread** [thiagorossener/jekflix-template#104]
Changing `site.yml`'s `paginate` setting as -1 will brake whole page.
changing site setting by netlify's cms automatically set paginate as -1.

**Comment by thiagorossener** [comment]
![image](https://user-images.githubusercontent.com/1750826/85643550-e56aed00-b66a-11ea-9cda-07ed0abf6a24.png)

Hey @Party4Bread, do you mean leaving the above field blank is making Netlify set it as -1?

I just tested it, and it didn't happen to me. The `paginate` simply doesn't appear on `site.yml` when I do that.

Could you explain what exactly did you do to reproduce it?

**Comment by Party4Bread** [comment]
I tried to reproduce it but can't make it.
Maybe it was just my typo. Sorry for false alarming.
