### ISSUE TITLE
Provide a copy of your Wiki

### ISSUE THREAD

**Issue by SriSatyaLokesh** [thiagorossener/jekflix-template#108]
Please let us know how to get this Wiki.
This is really good. You can create a repo or you can make `docs` folder and keep all this wiki. so that this is easily accessible

Thanks in advance

**Comment by thiagorossener** [comment]
Yeah, I've been thinking about moving the wiki for a while. I need to do more research what people have been doing with template documentation.

Thanks for let me know this is relevant.

**Comment by SriSatyaLokesh** [comment]
We can get this wiki locally with 
` git clone https://github.com/thiagorossener/jekflix-template.wiki.git`
May be you can add this in wiki and README.md
