### ISSUE TITLE
Paginate for Posts not working

### ISSUE THREAD

**Issue by puneethkanna** [thiagorossener/jekflix-template#110]
I used paginate: true for a post and used the divider --page-break--, but the page is not breaking and --page-break-- is shown in the site.

**Comment by thiagorossener** [comment]
Hey @puneethkanna, if you're using GitHub Pages to deploy your site, it's not going to work.

The template uses the `jekyll-paginate-content` plugin to do that, and unfortunately it's [not supported](https://pages.github.com/versions/).

If you really need that functionality, I suggest you to deploy on Netlify.

**Comment by puneethkanna** [comment]
@thiagorossener  Thank you, but if build my pages locally and push to github. Will it work..

**Comment by thiagorossener** [comment]
If you push only the content on the `_site` folder, yes. However, if you're using a fork of the repo, GitHub Pages will try to rebuild your site.

**Comment by puneethkanna** [comment]
Oh, thank you. I will try to build locally and push it. I will update the status here

**Comment by thiagorossener** [comment]
Nice, no problem. I thought I wrote that on the docs, but it wasn't there, just updated it. Thanks for let me know about this issue @puneethkanna
