### ISSUE TITLE
Issue with "Minutes To Read" Algorithm

### ISSUE THREAD

**Issue by madhavmehndiratta** [thiagorossener/jekflix-template#115]
The minutes to read also includes the text that we write in the code snippet. Since In my blog, I share a lot of code and terminal outputs, The minutes to read on an average shows 20-25 minutes to read. Currently, It divides the number of words by 180. One way to fix this is increasing this value to a larger number but this fails when there are not code blocks, Then it generally shows 2-3 minutes to read which is inaccurate. Is there a way that the minutes to read algorithm ignores the code snippets and count only the words I actually type?

`  {% assign totalMinutes = words | divided_by: 180 %}`

**Comment by thiagorossener** [comment]
Hi @madhavmehndiratta, unfortunately, the standard `number_of_words` [filter for Jekyll](https://jekyllrb.com/docs/liquid/filters/) only accepts arguments to fix issues with Chinese-Japanese-Korean characters and not code.

I believe you can either open an issue on [Jekyll repository](https://github.com/jekyll/jekyll) or create [your own filter](https://jekyllrb.com/docs/plugins/filters/) to count the words ignoring the code blocks.

In the case you want to go down the second road, you can base yours plugin on the [existent filter itself](https://github.com/jekyll/jekyll/blob/master/lib/jekyll/filters.rb#L124).
