### ISSUE TITLE
i want to remove code highlighter .

### ISSUE THREAD

**Issue by anuragseven** [thiagorossener/jekflix-template#117]
In want to add my own custom code highlighter . Please tell me how I can remove the highlighter that comes with the template.

**Comment by thiagorossener** [comment]
Hey @anuragseven, I haven't checked the repo for a while, so I'm sorry for taking that long.

If you still have that issue, it depends on how you're using the template:

1. If you installed it with the `gem`, you can create a file in `/assets/css/styles.scss` and add the following:
```scss
---
---

@import "jekflix";

[your styles go here]
```

2. If you cloned the template, you just need to edit the [_sass/_highlight.scss](https://github.com/thiagorossener/jekflix-template/blob/master/_sass/_highlight.scss)
