### ISSUE TITLE
Site deployed but incompletely

### ISSUE THREAD

**Issue by ElisonSherton** [thiagorossener/jekflix-template#124]
Hi Everyone!

Thanks Thiago for putting up such a wonderful website. I would like to use it for personal use and so 

1. I forked this repo https://github.com/thiagorossener/jekflix-template
2. I removed the CNAME file.
3. I added "/blog" to the baseurl in _config.yml file

This is how the deployed site looks. 

https://elisonsherton.github.io/jekflix-template/

I cannot understand where else should I change things to make it work properly. Any inputs would be highly appreciated.

**Comment by muhammedashfar7** [comment]
Hello👋
The link you provided is redirecting to 404 error. Please specify your exact problem that I can help you.
I also used this template and fixed almost all issues and edited.
Thank You❤
