### ISSUE TITLE
Hugo Version

### ISSUE THREAD

**Issue by stephenajulu** [thiagorossener/jekflix-template#126]
Hi, how are you?
First i would like to thank you for this amazing theme.
Would like to use it to build a multiauthor blog.
But i wanted to ask if you could kindly also develop a Hugo version
Why?
Hugo's build process is fast. 
It can build 100 pages in less than 20 seconds.

**Comment by stephenajulu** [comment]
Hugflix could be a good name

**Comment by thiagorossener** [comment]
Hey @stephenajulu, I'm good and you?

Glad you like the theme and thank you very much for your suggestion! Indeed it would be nice to develop the theme for others static site generators like Hugo.

However, unfortunately, I'm not able to do it at the moment. I'm even struggling to find time to respond and fix every issue people have been posting here.

Feel free to fork the project and implement it yourself, there is no problem in using the same design or code.

Have a great week!

**Comment by stephenajulu** [comment]
Thank you very much.
Will get back to you once i do as you've said.
Have a great day.
