### ISSUE TITLE
Error while trying to deploy in netlify

### ISSUE THREAD

**Issue by e-labInnovations** [thiagorossener/jekflix-template#127]
![image](https://user-images.githubusercontent.com/33958126/90723014-8b3c8000-e2d9-11ea-8de3-24c7cb400675.png)

[e-labinnovations.github.io](https://e-labinnovations.github.io)
[e-labinnovations.netlify.app/](https://e-labinnovations.netlify.app/)

**Comment by thiagorossener** [comment]
Thank you @e-labInnovations, I saw that error this week. You need to add `kramdown-parser-gfm` in your `Gemfile`.

Will update the theme when I have some time.

Thank you for your report.

**Comment by e-labInnovations** [comment]
Problem solved

**Comment by e-labInnovations** [comment]
![](https://i.imgur.com/tXyyFts.jpg)

How to solve this?

**Comment by thiagorossener** [comment]
You probably have to go through some steps first. Please, check the [docs](https://github.com/thiagorossener/jekflix-template/wiki/Netlify-CMS#integrate-with-netlify-cms).

I think you need to do [this](https://www.netlifycms.org/docs/add-to-your-site/#enable-identity-and-git-gateway), but I'm not sure.

**Comment by e-labInnovations** [comment]
hank you @thiagorossener 
It working
