### ISSUE TITLE
NOVO ARTIGO

### ISSUE THREAD

**Issue by javier-marroquin** [thiagorossener/jekflix-template#14]
Olá ótimo tópico, eu tenho uma pergunta. Como alterar o texto de "novo ARTIGO"?
Eu pesquisei e não consigo encontrar onde. Eu vejo em _include a seção "new-post-tag", mas só vemos que diz "{% assign isnewpost = true%}.

Hola gran tema, tengo una pregunta. ¿Cómo cambiar  el texto de "nuevo post" ?
He buscado y no encuentro donde. Veo en _include la seccion "new-post-tag" pero ahi solo se veo que dice "{% assign isnewpost = true %}.

Hello great topic, I have a question. How to change the text of "new post"?
I have searched and can not find where. I see in _include the section "new-post-tag" but there we only see that it says "{% assign isnewpost = true%}.

**Comment by thiagorossener** [comment]
Hello @javier-marroquin!

Sorry for the late response.

You just need to change the text in the class `.new-post:after` on `_home.styl` file.
