### ISSUE TITLE
ChildProcess spawn ENOENT when deploy using docker

### ISSUE THREAD

**Issue by AgnesLL** [thiagorossener/jekflix-template#146]
```
Error: spawn bundle ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:268:19)
    at onErrorNT (internal/child_process.js:470:16)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)
```
It works when I run the web server locally, but when I run on build a docker container and run it, the above error occurred.

**Comment by thiagorossener** [comment]
Hey @AgnesLL, I'm sorry for the late response, I haven't checked the repo for a while.

I'm not sure what could be happening, never ran it on Docker.

Check [that solution](https://github.com/forestryio/create-static-site/issues/42), may work for you.
