### ISSUE TITLE
Add escape to sitemap generator

### ISSUE THREAD

**Issue by jonboc** [thiagorossener/jekflix-template#156]
To ensure & can be used in titles and URLs and not invalidate the URLs in sitemap.xml the sitemap.xml needs escape adding as below:

 ```
---
layout: null
---
<?xml version="1.0" encoding="UTF-8"?>
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
    {% for page in site.pages %}
        <url>
            <loc>{{ page.url | prepend: site.baseurl | prepend: site.url | escape }}</loc>
            {% if page.layout == 'main' %}
                <changefreq>weekly</changefreq>
                <priority>1</priority>
                <lastmod>{{ site.time | date: "%Y-%m-%d" }}</lastmod>
            {% else %}
                <changefreq>monthly</changefreq>
                <priority>0.5</priority>
            {% endif %}
        </url>
    {% endfor %}
    {% for post in site.posts %}
        <url>
            <loc>{{ post.url | prepend: site.baseurl | prepend: site.url | escape }}</loc>
            <changefreq>weekly</changefreq>
            <priority>0.8</priority>
            <lastmod>{{ post.date | date: "%Y-%m-%d" }}</lastmod>
        </url>
    {% endfor %}
    {% for author in site.authors %}
        <url>
            <loc>{{ author.url | prepend: site.baseurl | prepend: site.url | escape }}</loc>
            <changefreq>monthly</changefreq>
            <priority>0.5</priority>
        </url>
    {% endfor %}
</urlset>
```

Hope this helps make an amazing template even better.

**Comment by netslutter** [comment]
> 
> 
> To ensure & can be used in titles and URLs and not invalidate the URLs in sitemap.xml the sitemap.xml needs escape adding as below:
> 
> ```
> ---
> layout: null
> ---
> <?xml version="1.0" encoding="UTF-8"?>
> <urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
>    {% for page in site.pages %}
>        <url>
>            <loc>{{ page.url | prepend: site.baseurl | prepend: site.url | escape }}</loc>
>            {% if page.layout == 'main' %}
>                <changefreq>weekly</changefreq>
>                <priority>1</priority>
>                <lastmod>{{ site.time | date: "%Y-%m-%d" }}</lastmod>
>            {% else %}
>                <changefreq>monthly</changefreq>
>                <priority>0.5</priority>
>            {% endif %}
>        </url>
>    {% endfor %}
>    {% for post in site.posts %}
>        <url>
>            <loc>{{ post.url | prepend: site.baseurl | prepend: site.url | escape }}</loc>
>            <changefreq>weekly</changefreq>
>            <priority>0.8</priority>
>            <lastmod>{{ post.date | date: "%Y-%m-%d" }}</lastmod>
>        </url>
>    {% endfor %}
>    {% for author in site.authors %}
>        <url>
>            <loc>{{ author.url | prepend: site.baseurl | prepend: site.url | escape }}</loc>
>            <changefreq>monthly</changefreq>
>            <priority>0.5</priority>
>        </url>
>    {% endfor %}
> </urlset>
> ```
> 
> Hope this helps make an amazing template even better.

Try to pull this as a request !

**Comment by thiagorossener** [comment]
Hey @jonboc, thank you. Please, submit a PR, so I can merge it.
