### ISSUE TITLE
SEO problem, unable to be searched

### ISSUE THREAD

**Issue by STUTuna** [thiagorossener/jekflix-template#158]
![image](https://user-images.githubusercontent.com/25971229/137764958-8a902417-f730-4332-8bba-e9b0f930b2e2.png)
The website I built using jekflix cannot be searched in google
Have tried to register in the google search console
And submit sitemap
But this tool still tells me that this website cannot be searched
My website: https://stutuna.github.io/
Am i missing something

**Comment by thiagorossener** [comment]
Hey @STUTuna, I just saw your issue. Apparently, everything looks fine with your `sitemap.xml`:
https://stutuna.github.io/sitemap.xml

I don't understand much about Google Analytics, so I think you'll have better luck in some forum or StackOverflow.
