### ISSUE TITLE
Bug with the top Navbar

### ISSUE THREAD

**Issue by NanoSpicer** [thiagorossener/jekflix-template#16]
When you close up the sidebar by clicking outside of it, it reduces the original size of the top navbar.

**Comment by krishnaanaril** [comment]
@NanoSpicer I tested in firefox, Chrome, IE11 and IE Edge. Did you get the same issue post the fix?

**Comment by NanoSpicer** [comment]
In my computer I have Chrome, Firefox and IE11.

* IE11: works as expected
* Chrome (V65 and V66): works as expected.
* Firefox  Quantum (V59): It doesn't. 

Now instead of having the bar moved aside the whole time, it gets aside when the menu is closed (after closing it by clicking outside of it) and when clicking the menu it gets at where, before clicking it, it should be.

1 Before any action
![imagen](https://user-images.githubusercontent.com/30906623/39326893-a6d4c234-4996-11e8-9c34-bd6236ebe2fa.png)

2 After clicking on the menu for the first time
![imagen](https://user-images.githubusercontent.com/30906623/39326927-c17c1f2e-4996-11e8-8b95-550fe2efd4f2.png)

3 After clicking outside the menu for the first time
![imagen](https://user-images.githubusercontent.com/30906623/39327002-f7bb535c-4996-11e8-979a-38c98f14bd96.png)

4 After clicking the menu again
![imagen](https://user-images.githubusercontent.com/30906623/39327032-15656442-4997-11e8-8554-ba28fd55c7d9.png)

5 After clicking outside the menu again
![imagen](https://user-images.githubusercontent.com/30906623/39327062-2c08d904-4997-11e8-9aa6-a4a015e22cf8.png)


*Side note*
I've noticed that 3, 4 and 5 get "autofixed" if some kind of window resizing or refreshing gets done on the browser.

**Comment by Soulthrower** [comment]
Fixed the problem cross browser adding 
left 0
to .bar-header in _header.styl. You can keep position fixed with this fix.

**Comment by thiagorossener** [comment]
Hey guys, thank you all for finding the bug and suggest a solution. Just pushed a commit to fix that [here](https://github.com/thiagorossener/jekflix-template/commit/1b0881e9db83e044b9c0df5ebccf9a8ac2be9cde).
