### ISSUE TITLE
How to disable latest post enlargement?

### ISSUE THREAD

**Issue by Pearl201** [thiagorossener/jekflix-template#162]
I apologize if I am asking a stupid question, is there any way I can show latest post similar to other posts? Without it being taking over half of the page?

**Comment by thiagorossener** [comment]
Hey @Pearl201, that's not stupid at all. I'm not sure if you're using this theme with a `gem` or you cloned it. But if you're using with a `gem` you can customize the theme.

Check out the Jekyll documentation:
https://jekyllrb.com/docs/themes/#overriding-theme-defaults

You'll find out that you need to create a `_sass` folder in your site and change some classes.

For _Jekflix_, you can simply import the theme:
https://github.com/thiagorossener/jekflix-template#theme-colors

Then change the sidebar styles as your wish.

**Comment by thiagorossener** [comment]
As for showing similar posts, you'd need to copy the entire `post.html` file, and replace this line:
https://github.com/thiagorossener/jekflix-template/blob/master/_layouts/post.html#L42

As Jekyll is a static generator, it's hard to tell what's a "similar" post. I think there is a way to get the posts with the same category, which may be enough for you.

**Comment by Pearl201** [comment]
Thank you so much for your help I would try out. Btw I have cloned the repo.

**Comment by Pearl201** [comment]
Thank you so much for your help I would try out. Btw I have cloned the repo.
