### ISSUE TITLE
Question about post creation

### ISSUE THREAD

**Issue by moakra** [thiagorossener/jekflix-template#17]
Hi,

I have a simple question about creating a new post. I changed the blog url in the initpost script with mine but I did not succeed to add a new post when I run:

`sh initpost.sh -c Introduction to multi agent systems`

The error is about a bad substitution. Do you have any idea from where this issue might come from ?

Thank you!

**Comment by thiagorossener** [comment]
Hi @moakra! Sorry for the late response.

I tried to run the code you posted, it created the post as expected. Please, try to run the command with the post name between quotes like:

```
sh initpost.sh -c "Introduction to multi agent systems"
```

If possible and it doesn't work, post the error here for further investigation.

**Comment by moakra** [comment]
Now it works. Thank you!
