### ISSUE TITLE
Style does not work after publishing using Github pages, but works fine locally.

### ISSUE THREAD

**Issue by ZhengLin-Li** [thiagorossener/jekflix-template#193]
Style does not work after publishing using Github pages, but works fine locally.

the repo of source code: https://github.com/ZhengLin-Li/ZhengLin-Li.github.io.jekflix

locally, OK:
![image](https://user-images.githubusercontent.com/63448884/213859970-50e9ecd2-930c-43b4-b0ac-9efe985f622f.png)

github pages, not OK:
![image](https://user-images.githubusercontent.com/63448884/213859982-2988bc46-15bf-4fd7-9d22-fb695b068aaa.png)

**Comment by AsyncSan** [comment]
Hey,

I had the same issue and finally got the solution after 2 hours lol.
You need to change the following in your _config.yml

baseurl: "/ZhengLin-Li.github.io.jekflix/"
url: "https://zhenglinli.me/ZhengLin-Li.github.io.jekflix/"

Thank me later

**Comment by ZhengLin-Li** [comment]
> 

ohhh, thank you a lot, that works for me.
