### ISSUE TITLE
Usability without Javascript?

### ISSUE THREAD

**Issue by paulcmal** [thiagorossener/jekflix-template#20]
Hi,

And thank you for making jekflix. I was trying to browse a website that uses your theme when i realized list templates don't display any article when Javascript is disabled.

There's many good reasons both for the client to disable Javascript (slow connection, security concerns) and for the webmaster to provide nice and accessible HTML/CSS. Here's a [nice presentation](https://sonniesedge.co.uk/talks/dear-developer) about such issues :)

In my personal opinion, Javascript should never be involved in presenting static content. Anyway, simply removing the opacity property from `.flex-grid article` in the CSS makes everything readable although it's probably not displayed right as it's supposed to.

I hope you find time and energy to make your theme more accessible and more lightweight with less client-side scripting. Have a great day!

**Comment by thiagorossener** [comment]
First of all, thank you @paulcmal for bringing this up.

Better late than never, I found some time today to improve a little bit the theme and make it work without JS with [few lines](https://github.com/thiagorossener/jekflix-template/commit/ac1cbe78be7516853ca173e9834863797266cae0).

I know there is a long journey to make it fully accessible, but it's a start :)

Just out of curiosity -  after a whole year - do you remember the website that was using my theme?
