### ISSUE TITLE
New Post tag in Firefox appears in wrong place

### ISSUE THREAD

**Issue by simoncourtenage** [thiagorossener/jekflix-template#21]
When viewed in Firefox, the new post icon appears to stick out behind the top-left corner of the image, not overlaid on the image near the bottom-left.  I'm not sufficiently clued-up on CSS to know why this is.  Thanks.

**Comment by thiagorossener** [comment]
Hey @simoncourtenage, could you provide a screenshot and the Firefox version you used to test it?

I've just opened the page in FF 65.0.1 and the label was in the right place.
