### ISSUE TITLE
help needed

### ISSUE THREAD

**Issue by khalidelmerrah** [thiagorossener/jekflix-template#27]
hello, 
i want to thank you for the great fast beautiful jekyll template you created, it's marvelous. i've looked everywhere in the web but found nothing like what you have made .. not for jekyll, thank you again. i would love to buy you a beer (the link on the readme doesn't work) but i want to ask you something if it's possible.. i want to have a sidebar on the post page it would be fantastic that way how can customize it to have a side bar ?? 

thank you .. about the beer ... i'm serious i really wanna buy u a beer 😄

**Comment by thiagorossener** [comment]
Hey @khalidelmerrah, thank you again, I'm really glad you liked it.

Did you get to create the sidebar as you wished?

And thanks for let me know the donation button wasn't working, I had no idea. Just fixed it!

**Comment by khalidelmerrah** [comment]
sure bro anytime .. yeah i had a responsiveness issue. but we should chat about that even further .. plenty things could be done here and possibly real income ;)
