### ISSUE TITLE
can't build with gulp

### ISSUE THREAD

**Issue by juunone** [thiagorossener/jekflix-template#29]
events.js:174
      throw er; // Unhandled 'error' event
      ^

Error: spawn bundle ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:240:19)
    at onErrorNT (internal/child_process.js:415:16)
    at process._tickCallback (internal/process/next_tick.js:63:19)
Emitted 'error' event at:
    at Process.ChildProcess._handle.onexit (internal/child_process.js:246:12)
    at onErrorNT (internal/child_process.js:415:16)
    at process._tickCallback (internal/process/next_tick.js:63:19)

- npm install 
- npm install -g gulp gulp-cli
- gulp

step by step but that error message show 
os: mac os mojave
node: v10.15.3

i search google long time but cant solve this problem
i try to killall -9 node and node version change lot things..

**Comment by thiagorossener** [comment]
Can you run `bundle exec jekyll build`? Doest it work?

**Comment by juunone** [comment]
OMG yes u right !
i miss it..thanks
i forgot bc i got change my env
thanks appreciate!

**Comment by Muffo** [comment]
This worked great! Should it be added to the README?
Or maybe it's based on the assumption people will have already executed this. I am new to Jekyll so I am not really sure what people generally do.

Btw, this theme is really great! :)

**Comment by thiagorossener** [comment]
@Muffo I added it to the [new version docs](https://github.com/thiagorossener/jekflix-template/wiki/setup#installing-template). Thank you for bring this up.

**Comment by Muffo** [comment]
Thanks a lot!
