### ISSUE TITLE
Can't start with gulp

### ISSUE THREAD

**Issue by ayrat555** [thiagorossener/jekflix-template#3]
Application can't load assets with 'sudo gulp' command.
[screenshot](https://i.imgur.com/Qr7iYX0.png)

Works fine with 'bundle exec jekyll serve' but to refresh assets you need to run 'sudo gulp'

**Comment by nwsnate** [comment]
Same here

**Comment by CalebKing3** [comment]
Found the fix, it was related to the _config.yml.

If you are working locally then `baseurl` and `url` need to be left blank. `""`

Just not when you deploy on your site you will need to update
