### ISSUE TITLE
Gulp 4

### ISSUE THREAD

**Issue by siclemx** [thiagorossener/jekflix-template#30]
Hi! 

Since gulp 4 has major changes you have to update gulpfile.js in order to build jekflix correctly.

Could you update that file please?

I've made those changes if you don't mind a PR.

Regards!

**Comment by thiagorossener** [comment]
Hey, thanks for let me know.

Sure! Send the PR, I'll look into it as soon as I can.

**Comment by siclemx** [comment]
Hello @thiagorossener 

PR #31 sent :)

**Comment by thiagorossener** [comment]
Thank you @siclemx, I've noticed some things weren't working properly, so I enhanced the `gulpfile.js`.

You can check it out here:
https://github.com/thiagorossener/jekflix-template/blob/master/gulpfile.js

**Comment by siclemx** [comment]
Awesome! thank you @thiagorossener
