### ISSUE TITLE
Suggestion: Make it easier to move to a newer version of Jekflix

### ISSUE THREAD

**Issue by aeternesatiatus** [thiagorossener/jekflix-template#38]
It'd be awesome if you could make a bash script that manually updated all the theme files so that we don't have to make a brand new website if we need to move to a newer version of Jekflix.
(maybe backup the old config file if the new one changes)

**Comment by thiagorossener** [comment]
Hey @aeternesatiatus, I've just pushed a new version of _Jekflix_ that allows you to install the theme using a `gem`.

Check out the [docs](https://github.com/thiagorossener/jekflix-template#quick-install).

After making the changes needed, you can simply run `$ bundle update` every time I publish a new version.
