### ISSUE TITLE
Netlify CMS giving error No branch Found

### ISSUE THREAD

**Issue by aeternesatiatus** [thiagorossener/jekflix-template#39]
I've followed the steps from https://www.netlifycms.org/docs/add-to-your-site/#enable-identity-and-git-gateway to set up the cms and invites a few members.
However, they all get a "no branch found" error when trying to log in.
Is this because of Jekflix?

**Comment by thiagorossener** [comment]
It's unlikely. Check your Netlify settings in **Settings > Build & Deploy > Deploy contexts** 

![Screen Shot 2019-09-06 at 21 23 50](https://user-images.githubusercontent.com/1750826/64467192-c8215e00-d0ec-11e9-942c-5036fbff7001.png)

**Comment by aeternesatiatus** [comment]
I followed all the steps properly and still get the error.
It lets me log in but then switches back to the admin home page and doesn't let me access the dashboard... Keeps saying no branch found, does it work on your website?
I've only tried using it with one account after verification...

**Comment by aeternesatiatus** [comment]
Branch not found

**Comment by aeternesatiatus** [comment]
got it working!! https://github.com/hackdown-org/fr.hackdown.org/commit/22b73a9f5235fada11aa9ebaabddacc40f655c75
maybe change everything to master by default or explain this in the README.md :)
You can close the issue!

**Comment by thiagorossener** [comment]
Nice! Thanks for pointing this out, just fixed it.
