### ISSUE TITLE
Error about time zone

### ISSUE THREAD

**Issue by ghost** [thiagorossener/jekflix-template#4]
Hi thiagorossener, thanks for your nice work. 

I found a small bug about time zone, maybe you could fix it:
Any post whose date time is earlier than central time zone will not be shown on the website.

**Comment by thiagorossener** [comment]
Hi @hongxinliu! Thank you, it's very cool you enjoyed my work and sorry for the late answer.

Nice, I will take a look as soon as possible, I've been very busy these days, so it's hard to say when.

Thank you for tell me about this issue, and feel free to send me a PR if you think you could help with this.
