### ISSUE TITLE
Login in: Failed to load settings from /.netlify/identity

### ISSUE THREAD

**Issue by BecomeDataScientist** [thiagorossener/jekflix-template#41]
I have a problem when i trying access admin page username.github.io/admin. Specifically, i get an error "Failed to load settings from /.netlify/identity". Some one can help me solve it plz

**Comment by thiagorossener** [comment]
@BecomeDataScientist have you deployed your website with [Netlify](https://github.com/thiagorossener/jekflix-template/wiki/netlify-cms#deploy-with-netlify)?
