### ISSUE TITLE
code syntax highlighting problem

### ISSUE THREAD

**Issue by dantory** [thiagorossener/jekflix-template#42]
Hi. 

I have a problem when code syntax highlighting

## source code - 1

<pre>
```js
// Example can be run directly in your JavaScript console

// Create a function that takes two arguments and returns the sum of those arguments
var adder = new Function("a", "b", "return a + b");

// Call the function
adder(2, 6);
// > 8
```
</pre>

## result - 1

![Screenshot 2019-09-22 15 36 04](https://user-images.githubusercontent.com/26054516/65383312-ba0b4880-dd4e-11e9-9775-2dd8ca7cf050.png)

## source code - 2

<pre>
``` js
const errorMsg = 'the # is not even';
for (let number = 2; number <= 5; number += 1) {
    console.log('the # is ' + number);
    console.assert(number % 2 === 0, {number: number, errorMsg: errorMsg});
    // or, using ES2015 object property shorthand:
    // console.assert(number % 2 === 0, {number, errorMsg});
}
```
</pre>

## result - 2

![Screenshot 2019-09-22 15 41 30](https://user-images.githubusercontent.com/26054516/65383369-aad8ca80-dd4f-11e9-9c75-0e478d0d0d8f.png)

Maybe the [fenced code block](https://help.github.com/en/articles/creating-and-highlighting-code-blocks) is the problem.

If you do the [liquid tag](https://jekyllrb.com/docs/liquid/tags/), it works fine.

Is there a solution?

**Comment by thiagorossener** [comment]
Hi @dantory, can you show the result for the liquid tag? I tried it and it looks the same for me.

Anyway, you can edit the highlight styles in `/src/styl/_highlight.styl`.

**Comment by Thelta** [comment]
The problem isn't about highlighting. In code blocks, some characters are modified. '=' becomes '~|=|', '#' becomes '~|=|' etc.

**Comment by thiagorossener** [comment]
Wow! Now I see it, sorry for that.

I tried to find a solution, but could not.

@dantory is it happening locally? I checked your page and it looks fine:
https://dantory.netlify.com/welcome-to-the-desert-of-the-real/2/

If so, could you check the `kramdown` and `rouge` versions please?

```
$ bundle show kramdown
```

And

```
$ bundle show rouge
```
