### ISSUE TITLE
404 page not displayed

### ISSUE THREAD

**Issue by worming004** [thiagorossener/jekflix-template#45]
Hello,

404 page are not shown.
https://jekflix.rossener.com/unknown

This page is displayed instead 
![image](https://user-images.githubusercontent.com/23192591/65386412-b621fb00-dd3b-11e9-913d-dca8f224e607.png)

**Comment by worming004** [comment]
Linked to https://github.com/thiagorossener/jekflix-template/pull/46

**Comment by thiagorossener** [comment]
Thank you again.
