### ISSUE TITLE
Disqus not loading comments section

### ISSUE THREAD

**Issue by anisabek** [thiagorossener/jekflix-template#48]
I created a disqus account and changed my username as instructed but I am getting this error
**"We were unable to load Disqus. If you are a moderator please see our troubleshooting guide."**

Anyone knows how to fix this issue?

**Comment by thiagorossener** [comment]
@anisabek this is strange, how is your Disqus settings?

This page:
![image](https://user-images.githubusercontent.com/1750826/66707768-b569fc80-ed1c-11e9-98c4-288946ef1016.png)

**Comment by anisabek** [comment]
![disqus](https://user-images.githubusercontent.com/54504560/66732500-8490e100-ee5c-11e9-9a8c-4d4379a8de31.png)

**Comment by thiagorossener** [comment]
Hey @anisabek, I see what might be the issue. The _Website Name_  is the **disqus_username** property you need to set in Jekyll.

Try set the _Website Name_ in Disqus and the _disqus_username_ in Jekyll to just `anisabek` (no dots) and check if it works.

**Comment by anisabek** [comment]
Done that, but same problem and error

**Comment by thiagorossener** [comment]
@anisabek this is weird. Really don't know what's going on, try reach out for Disqus support, they might have a better clue
