### ISSUE TITLE
Error about setting GitHub Pages

### ISSUE THREAD

**Issue by miniesam** [thiagorossener/jekflix-template#49]
I see this error message on the repository's Settings page.
I wonder what's the problem.

```
Your site is having problems building: The tag toc on line 30 in /_layouts/post.html is not a recognized Liquid tag. For more information, see https://help.github.com/en/articles/troubleshooting-jekyll-build-errors-for-github-pages-sites#unknown-tag-error.
```

**Comment by thiagorossener** [comment]
@miniesam this is a plugin I recently added to the theme to handle [Table of Contents](https://github.com/toshimaru/jekyll-toc).

Try to run `bundle install` in the root of your project to install all the gems.

**Comment by miniesam** [comment]
@thiagorossener, I'm afraid nothing has changed and I cannot push files to the repository.

**Comment by thiagorossener** [comment]
@miniesam I've just checked the list of GitHub pages [supported packages](https://pages.github.com/versions/) and it doesn't support `jekyll-toc` plugin.

I'm sorry, I didn't know that. Just removed it from the repo, try to pull in the latest changes, it should work now.

**Comment by miniesam** [comment]
That's good news, @thiagorossener!
And thank you for making a great Jekyll theme!
