### ISSUE TITLE
Category page says 404

### ISSUE THREAD

**Issue by venilnoronha** [thiagorossener/jekflix-template#5]
Hi,

I observed this issue where clicking on a post category on homepage redirects to the 404 page. Is this a known issue?

Thanks,
Venil

**Comment by thiagorossener** [comment]
Sorry for the pretty late response @venilnoronha.

I just created the category layout. So, to create the category pages you have to add a file named like `category/category-name.md` with the content:

```
---
layout: category
category: 'category-name'
---
```

**Comment by garethjax** [comment]
Hi, would it possible to auto-create the category pages  ?
