### ISSUE TITLE
Link para a imagem off.jpg incorreto

### ISSUE THREAD

**Issue by sidneiweber** [thiagorossener/jekflix-template#50]
Nos arquivos abaixo a imagem off.jpg está sendo linkada para off.png. Tentei abrir um PR mas acho que não tenho permissão.

_includes/modal.html
_includes/recommendation.html
_layouts/post.html

 assets/img/off.jpg

**Comment by thiagorossener** [comment]
@sidneiweber deveria dar pra abrir PR sim, já recebi alguns por aqui, não sei o que pode tá acontecendo.

De qualquer forma, muito obrigado pelo aviso! Acabei de fazer as alterações pra corrigir isso 😄
