### ISSUE TITLE
Providing a gem

### ISSUE THREAD

**Issue by noraj** [thiagorossener/jekflix-template#51]
Can you provide a gem on Ruygems `jekyll-jekflix`.

See https://jekyllrb.com/docs/themes/#understanding-gem-based-themes

So one could add `gem "jekyll-jekflix"` in its Gemfile and `theme: jekflix` in `_config.yml` when wanting to change a theme and easily update it.

**Comment by thiagorossener** [comment]
Hi @noraj, thank you for all the issues you pointed out this last week. I really appreciate all the time you put in to analyze the theme.

Creating a gem is something that is in my to-do list for a while, it's nice that you brought this up.

I'll try to create it and sort all the other things out ASAP, hopefully by the end of the year.

**Comment by thiagorossener** [comment]
Hey @noraj, I finally got the chance to create the `gem`.

I had to change **a lot** of stuff, but it's done. Now people can easily install and update the theme.

Thank you for your suggestion, check the docs:
https://github.com/thiagorossener/jekflix-template#quick-install

Please, if you find something wrong or missing in the docs, let me know. There are some things that still need updates.

**Comment by noraj** [comment]
@thiagorossener Very nice, as your theme is one of the most famous, it will be handy for a lot of people.
