### ISSUE TITLE
Wiki: setup lacks a step

### ISSUE THREAD

**Issue by noraj** [thiagorossener/jekflix-template#52]
The setup steps lacks of `bundle install` (install ruby dependencies) step.

https://github.com/thiagorossener/jekflix-template/wiki/setup#environment

**Comment by noraj** [comment]
Also need `npm install gulp-cli -g` to get `gulp` in PATH.

**Comment by thiagorossener** [comment]
I've just added those two steps into the documentation, thanks again @noraj!
