### ISSUE TITLE
Toolbar does not return to normal position when closing the menu

### ISSUE THREAD

**Issue by Zackazt** [thiagorossener/jekflix-template#6]
I am using Firefox 57. 

To recreate the issue:

1. Click the menu button in the top left corner to open it.
2. Click out of the menu to close it.

At this point the menu will remain displaced, but the menu will close.
<img width="1661" alt="screen shot 2017-11-15 at 11 01 03 am" src="https://user-images.githubusercontent.com/12701185/32852143-55a90748-c9f4-11e7-9a20-fa6cafe3cafa.png">

**Comment by thiagorossener** [comment]
Hey @Zackazt, sorry the late answer.

Thank you for notice that! I'm aware of the issue and I'll take a look ASAP.

If eventually you fix this, please don't hesitate to send me a PR.

**Comment by Zackazt** [comment]
I've created a pull request with a fix to the bug. Tested in all desktop browsers. No breaking changes were made so all original compatibility was retained with the addition of the new Firefox.
