### ISSUE TITLE
Feed XML file does not have style info 

### ISSUE THREAD

**Issue by iJalal** [thiagorossener/jekflix-template#60]
When you go into Feed section in [website,](https://jekflix.rossener.com/feed.xml) it gives this error:

This XML file does not appear to have any style information associated with it. The document tree is shown below.

And it just shows the website code instead of an actual page.

This is also the case in my own site I created using your template.

**Comment by thiagorossener** [comment]
Hi @iJalal, the `feed.xml` is used by RSS Readers, see a list of these apps [here](https://zapier.com/blog/best-rss-feed-reader-apps/).

There are Chrome/Firefox extensions that work like readers as well, so when you're in one of those apps you just paste the feed URL like [https://rossener.com/feed.xml](https://rossener.com/feed.xml) and it keeps you up-to-date with the website content.

It's made to have no style, just XML code for these apps.
