### ISSUE TITLE
Disqus doesn't work

### ISSUE THREAD

**Issue by iJalal** [thiagorossener/jekflix-template#61]
I set up a Disqus account & enter the username but it doesn't work on the template.

This same error is displayed in all of the Posts in your template website.

**Comment by thiagorossener** [comment]
Hi @iJalal, help me understand what is happening by answering these questions:

1. Are you using the `gem` template or you cloned the repo?
2. Did you add the `disqus_username` variable into your `_config.yml`?
3. Could you post a screenshot of the error?

**Comment by iJalal** [comment]
Hey Thiago!

I realized the issue was because of the Disqus_Username: _______
The word "Username" confused me into putting my account username in there when it is actually supposed to be the website shortname you registered into Disqus. 

I.E. Staywoke.Disqus.com is my website with Disqus
Whereas my actual username is Jalalibrahimi
I had the Disqus_Username set to Jalalibrahimi but when I changed it to Staywoke everything worked perfectly.

**Comment by thiagorossener** [comment]
Glad you figured it out @iJalal, thank you for the feedback.

**Comment by YeonghyeonKO** [comment]
@iJalal I have the same problem as you had.
In the below screenshot, my username is "disqus_wOQEYVXG8L", it doesn't seem like your username.
I added it to _config.yml and site.yml but the comment function is not operating...

![image](https://user-images.githubusercontent.com/46114393/85925046-046ab880-b8d1-11ea-822f-9a479e580f8b.png)

**Comment by benkenobi007** [comment]
@YeonghyeonKO  it is 2 years late, but posting the solution just for others who are trying to add Disqus to Jekflix

You need to go to disqus.com, click on "I want to install Disqus on my site", and then setup your site name -
![image](https://user-images.githubusercontent.com/21176284/184095505-f6636709-f279-4fbf-9c24-403543cfcfaf.png)

The **Website Name** in Disqus is what you need to fill in the **disqus_username** field.

So you would need to set it as -
`disqus_username: myrandomname`

And it should work perfectly.
