### ISSUE TITLE
Branch not found Error when CMS Login

### ISSUE THREAD

**Issue by Party4Bread** [thiagorossener/jekflix-template#62]
![image](https://user-images.githubusercontent.com/6923985/74456544-597dd300-4eca-11ea-9d33-7b7d5bbe27b7.png)
Seems likely to #39 
but can't find solution
![image](https://user-images.githubusercontent.com/6923985/74457311-6f3fc800-4ecb-11ea-836c-d97bb69a27ad.png)
here is my deploy setting.

**Comment by thiagorossener** [comment]
Hi @Party4Bread, you need to change the branch in your `admin/config.yml` from `gem` to `master`, it's in the third line.

I forgot to change it back to `master`, just [did](https://github.com/thiagorossener/jekflix-template/commit/e3a3c6701266dfa71162903688d22e8de7c9dec3) it.

Thank you for pointing this out.

**Comment by Party4Bread** [comment]
Thanks for quick resolve and this awesome template! That fix the issue.
