### ISSUE TITLE
On CMS Editor Unsaved Changes displayed even without any change in post

### ISSUE THREAD

**Issue by Party4Bread** [thiagorossener/jekflix-template#63]
![image](https://user-images.githubusercontent.com/6923985/74589440-bf906480-5048-11ea-9b1c-7b622f646a15.png)
That message comes up and make it unpublishable on editor screen.
Probably It is related to https://github.com/netlify/netlify-cms/issues/2211?
Or automatic change something like sanitizing unicode happened?

**Comment by thiagorossener** [comment]
Hmmm I believe it has something to do with that issue. I'm having the same problem, will need to look closer into this.

**Comment by thiagorossener** [comment]
It seems to be fixed in the latest Netlify CMS version.
