### ISSUE TITLE
Facebook Sharing Feature is broken

### ISSUE THREAD

**Issue by lukalafaye** [thiagorossener/jekflix-template#70]
![image](https://user-images.githubusercontent.com/31606786/75635422-12cdfe00-5c6a-11ea-9faa-3fd8f3a8dea0.png)

When trying to share a facebook url, I get an href error.

Can you please fix this?

**Comment by thiagorossener** [comment]
Hey @lukalafaye, I'm sorry for the delay.

It's not broken, you just need to change the settings:
- If you're deploying into GitHub Pages or using the `gem`, you need to add your website's URL in `_config.yml` located in the root of your theme, for example: `url: "https://jekflix.rossener.com"`
- If you're deploying into Netlify or building somewhere else with Gulp, you need to change the site's URL in `src/yml/advanced.yml`

Let me know if you're still having trouble.
