### ISSUE TITLE
How can I customize width of posts and style of code snippets?

### ISSUE THREAD

**Issue by tlonist-sang** [thiagorossener/jekflix-template#83]
I'm writing posts regarding some topics in computer science, and sometimes I feel the width is too narrow and the fact that the writing is always left-aligned doesn't help with readability. Also I'd like to know if one can customize the style of codes inserted in the postings. Thanks!

**Comment by thiagorossener** [comment]
Hey @tlonist-sang, sorry for taking so long.

1. To change the layout to one column and get a larger width, check the [docs](https://github.com/thiagorossener/jekflix-template/wiki/settings#two_columns_layout).
2. You can customize the code style only if you forked the repo (not if you're using the `gem`), in that case, check the file `/sass/_highlight.scss`.
