### ISSUE TITLE
New category title is not showing. It showing {{slug}} instead

### ISSUE THREAD

**Issue by muhammedashfar7** [thiagorossener/jekflix-template#85]
Title of the category is showing. It just showing {{slug}}. How can  I fix it.

**Comment by thiagorossener** [comment]
Hi @muhammedashfar7, did you create the `.md` file? Check the [docs](https://github.com/thiagorossener/jekflix-template/wiki/post#category).

Your category file should look like:
```
---
layout: category
title: Blog
slug: blog
description: A thread for blog posts.
permalink: /category/blog/
---
```
