### ISSUE TITLE
search not working

### ISSUE THREAD

**Issue by hellrider9** [thiagorossener/jekflix-template#87]
I haven't changed any thing just created some  posts and edited the yml files to make the website work on my github page,like changing the baseurl.

**Comment by thiagorossener** [comment]
Hi @hellrider9, did you fork the repo or is using the `gem`? Can you provide a link for your site?

**Comment by hellrider9** [comment]
I have forked the repo.Here is the link to the website http://hellrider9.github.io/writeup/

**Comment by thiagorossener** [comment]
Hmm this is weird, it can't find the `seach.json` file. Might be something related to GitHub pages, here is a documentation about how to check for errors:
https://help.github.com/en/github/working-with-github-pages/about-jekyll-build-errors-for-github-pages-sites

Is the search working locally?

**Comment by hellrider9** [comment]
Nope, it is not working locally. Here i am attaching the image of the command run "bundle exec jekyll serve
![Screenshot from 2020-05-22 01-06-08](https://user-images.githubusercontent.com/56410386/82598639-9c85cb80-9bc8-11ea-8d5b-f0ada5e78c31.png)

**Comment by hellrider9** [comment]
When i changed the baseurl to "" in advanced.yml then the search started working

**Comment by thiagorossener** [comment]
Yeah, the baseurl won't work locally. I think I found the issue.

1. Leave the baseurl as is, with "/writeup"
2. Go to `src/js/main/simpleJekyllSearch.js` locally
3. In the fourth line, change `/search.json` to `/writeup/search.json`
4. Run `gulp build`
5. Push those changes

I think this script is referencing the root of your site, so it can't find it.

If you go to this address, you'll see it's in there:
https://hellrider9.github.io/writeup/search.json

**Comment by hellrider9** [comment]
Thanks Man. It works now and again thanks for this wonderful theme.
