### ISSUE TITLE
Contact page doesn't work

### ISSUE THREAD

**Issue by atlas0603** [thiagorossener/jekflix-template#90]
When I click contact button, it goes from contact page to home automatically and immediately.
Contact page doesn't show up anyway.

**Comment by thiagorossener** [comment]
Hey @atlas0603, are you using the `gem` or did you clone the repo?

**Comment by atlas0603** [comment]
I'm using the gem

**Comment by muhammedashfar7** [comment]
Let me see your repo.

**Comment by atlas0603** [comment]
I noticed that the reason why contact pages didn't work is that I deleted email address in yml file. Now it is working correctly. Sorry for my misunderstanding.
