### ISSUE TITLE
Recommendation Customization

### ISSUE THREAD

**Issue by ryan2fp** [thiagorossener/jekflix-template#97]
Impressive Theme For Jekyll, Well Done !

https://imgur.com/qpaHQEG

But how to change the "Read Now" text, where's the specific configuration or script to make some customization here ?

I wanna change "Read Now" text into something else, how can I achieve this ? Please specify the configuration or relate script to make it happen.

**Comment by thiagorossener** [comment]
Hey @ryan2fp, thanks. You can customize the text through the translations file:
https://github.com/thiagorossener/jekflix-template/wiki/setup#translations
